/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemas.userInterface;

import javax.swing.JOptionPane;
import br.com.sistemas.model.database.ConexaoBDPostgres;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Larissa
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    
    ConexaoBDPostgres conexao;
    
    public TelaCadastroUsuario(ConexaoBDPostgres conexao) {
        this.conexao = conexao;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFuncao = new javax.swing.JComboBox<>();
        jLabelErroCPF = new javax.swing.JLabel();
        jLabelErroNome = new javax.swing.JLabel();
        jLabelErroSenha = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuario");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(652, 440));
        setMinimumSize(new java.awt.Dimension(652, 440));
        setResizable(false);

        jButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNome.setText("Nome");

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabelSenha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSenha.setText("Senha");

        jPasswordFieldSenha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCPF.setText("CPF");

        jTextFieldCPF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Função");

        jComboBoxFuncao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Estoquista" }));

        jLabelErroCPF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErroCPF.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelErroCPF.setText(" ");

        jLabelErroNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErroNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelErroNome.setText(" ");

        jLabelErroSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErroSenha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelErroSenha.setText(" ");

        jLabelError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jPasswordFieldSenha)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFuncao, 0, 539, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSenha)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelErroSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldCPF)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelErroCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelErroNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFuncao)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jLabelErroCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelErroNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelErroSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabelError)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(668, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // Coleta funcao, cpf, nome e senha das caixas de texto da interface
        String funcao = ((String)jComboBoxFuncao.getSelectedItem()).toLowerCase();
        String cpf = jTextFieldCPF.getText();
        String username = jTextFieldUsername.getText().toLowerCase();
        String senha = jPasswordFieldSenha.getText();
        // Verificacao de nulo para toda caixa de texto
        if(cpf.isBlank()){
            jLabelErroCPF.setText("Não pode ser nulo");
        } else{
            jLabelErroCPF.setText(" ");
        }
        if(username.isBlank()){
            jLabelErroNome.setText("Não pode ser nulo");
        } else{
            jLabelErroNome.setText(" ");
        }
        if(senha.isBlank()){
            jLabelErroSenha.setText("Não pode ser nulo");
        } else{
            jLabelErroSenha.setText(" ");
        }

        // Caso nenhum campo for nulo, execute:
        if(!cpf.isBlank() && !username.isBlank() && !senha.isBlank()){
            //log-in como admin para registrar usuários
            try {
                conexao.conectar();
                PreparedStatement ps;
                String sql;

                // Cria o usuário e dá as permissões da funcao (role) pra ele.
                // Prefixada e sufixada a letra u no nome do usuário pois o postgre não aceita usuários completamente numéricos
                sql = "CREATE USER u" + cpf + "u WITH PASSWORD '" + senha + "';"
                + "GRANT " + funcao + " to u" + cpf + "u;"
                + "CALL insert_tb_funcionarios('" + username + "', '" + cpf + "', '" + senha + "', '" + funcao + "');";
                ps = conexao.getConexao().prepareStatement(sql);
                ps.executeUpdate();

                // Encerra a transação e mostra mensagam de sucesso
                ps.close();
                JOptionPane.showMessageDialog(this, "Registrado usuário " + cpf + " (" + username + ")" + " com sucesso!");
                dispose(); // Auto-fecha janela de cadastro;
            } catch (SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JComboBox<String> jComboBoxFuncao;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelErroCPF;
    private javax.swing.JLabel jLabelErroNome;
    private javax.swing.JLabel jLabelErroSenha;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
