/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemas.userInterface;

import br.com.sistemas.model.database.ConexaoBDPostgres;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author Bastos
 */
    
public class TelaCadastroProduto extends javax.swing.JFrame {

    ConexaoBDPostgres conexaoBD;
    public TelaCadastroProduto(ConexaoBDPostgres conexaoBD) {
    this.conexaoBD = conexaoBD;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQuantidade = new javax.swing.JLabel();
        quantidadeProduto = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        valorProduto = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        descricaoProduto = new javax.swing.JTextField();
        jLabelFornecedor = new javax.swing.JLabel();
        fornecedorProduto = new javax.swing.JTextField();
        buttonAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelQuantidade.setText("Quantidade");

        quantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeProdutoActionPerformed(evt);
            }
        });

        jLabelPreco.setText("Valor");

        valorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProdutoActionPerformed(evt);
            }
        });

        jLabelDescricao.setText("Descrição");

        descricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoProdutoActionPerformed(evt);
            }
        });

        jLabelFornecedor.setText("Fornecedor");

        fornecedorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorProdutoActionPerformed(evt);
            }
        });

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelQuantidade)
                    .addComponent(jLabelPreco)
                    .addComponent(jLabelDescricao)
                    .addComponent(jLabelFornecedor)
                    .addComponent(fornecedorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(descricaoProduto)
                    .addComponent(valorProduto)
                    .addComponent(quantidadeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
    
    // Criando um objeto da classe de conexão

    Connection conexao = conexaoBD.getConexao();

    // Pegando os valores dos campos de texto
    String pro_descricao = descricaoProduto.getText();
    double pro_valor;
    int pro_quantidade;

    try {
        pro_valor = Double.parseDouble(valorProduto.getText());
        pro_quantidade = Integer.parseInt(quantidadeProduto.getText());
    } catch (NumberFormatException e) {
        System.out.println("Erro: Certifique-se de que o preço e a quantidade são números válidos.");
        return;
    }

    // Query SQL
    String sql = "INSERT INTO tb_produtos (pro_descricao, pro_valor, pro_quantidade) VALUES (?, ?, ?)";

    // Conexão com o banco e inserção dos dados
    try (PreparedStatement stmt = conexao.prepareStatement(sql)) {

        stmt.setString(1, pro_descricao);
        stmt.setDouble(2, pro_valor);
        stmt.setInt(3, pro_quantidade);

        int linhasAfetadas = stmt.executeUpdate();
        System.out.println("✅ Produto inserido com sucesso! Linhas afetadas: " + linhasAfetadas);

    } catch (Exception e) {
        System.out.println(e.getMessage());
    } finally {
        // Fechar conexão após o uso
        conexaoBD.disconnect();
    }
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void valorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProdutoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_valorProdutoActionPerformed

    private void quantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeProdutoActionPerformed

    private void descricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoProdutoActionPerformed

    private void fornecedorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JTextField descricaoProduto;
    private javax.swing.JTextField fornecedorProduto;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JTextField quantidadeProduto;
    private javax.swing.JTextField valorProduto;
    // End of variables declaration//GEN-END:variables
}
