
package br.com.sistemas.userInterface;

import br.com.sistemas.model.database.ConexaoBDPostgres;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bastos
 */
public class TelaAtualizarEstoque extends javax.swing.JFrame {

    ConexaoBDPostgres conexao;
        DefaultTableModel modelo = new DefaultTableModel(new Object [][] { },
            new String [] { "Código", "Descrição", "Quantidade"});
    
    public TelaAtualizarEstoque(ConexaoBDPostgres conexao) {
        this.conexao = conexao;
        initComponents();
    }
    
    public final void carregarProdutos() {
        String busca = jTextFieldBuscar.getText();
        if(busca.isBlank()){
            jLabelMensagemErroCodigo.setForeground(Color.red);
        } else{
            jLabelMensagemErroCodigo.setForeground(new Color(214, 217, 223));
            String sql = "SELECT * FROM tb_produtos WHERE pro_codigo = " + busca + ";";
            try  (PreparedStatement ps = conexao.getConexao().prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
                    while(modelo.getRowCount() > 0) {
                        modelo.removeRow(0);
                    }
                    while (rs.next()) {
                        Vector linha = new Vector();
                        linha.add(rs.getInt("pro_codigo"));
                        linha.add(rs.getString("pro_descricao"));
                        linha.add(rs.getInt("pro_quantidade"));
                        modelo.addRow(linha);
                    }
                    ps.close();
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }
    
    public void entradaDeProduto(){
        int quantidadeEntrada = (int)jSpinnerSeletorQuantidadeAdd.getValue();
        String sql = "CALL entrada_produto('" + (int)modelo.getValueAt(0, 0) + "', '" + quantidadeEntrada + "');";
        try{
            PreparedStatement ps = conexao.getConexao().prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Erro" + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinnerSeletorQuantidadeAdd = new javax.swing.JSpinner();
        jButtonAdicionar = new javax.swing.JButton();
        jLabelMensagemErroCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização de Estoque");

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID do Produto");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(modelo);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jSpinnerSeletorQuantidadeAdd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSeletorQuantidadeAddStateChanged(evt);
            }
        });

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jLabelMensagemErroCodigo.setForeground(new java.awt.Color(214, 217, 223));
        jLabelMensagemErroCodigo.setText("Insira o ID do Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerSeletorQuantidadeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabelMensagemErroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMensagemErroCodigo))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerSeletorQuantidadeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        if(modelo.getRowCount() == 0){
            jLabelMensagemErroCodigo.setForeground(Color.red);
        } else{
            entradaDeProduto();
            carregarProdutos();
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jSpinnerSeletorQuantidadeAddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSeletorQuantidadeAddStateChanged
        if((int)jSpinnerSeletorQuantidadeAdd.getValue() < 0){
            jSpinnerSeletorQuantidadeAdd.setValue(0);
        }
    }//GEN-LAST:event_jSpinnerSeletorQuantidadeAddStateChanged

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        carregarProdutos();
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensagemErroCodigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerSeletorQuantidadeAdd;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
