/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemas.userInterface;

import br.com.sistemas.model.database.ConexaoBDPostgres;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bastos
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    
    ConexaoBDPostgres conexao;
    DefaultTableModel modelo = new DefaultTableModel(new Object [][] { },
            new String [] { "Código", "Descrição", "Quantidade" , "Valor Un", "Valor Total"});
    
    public TelaVenda(ConexaoBDPostgres conexao) {
        this.conexao = conexao;
        initComponents();
    }
    
    public final void atualizarLista() {
        int quantidadeVenda = (int)seletorDeQuantidadeDeVenda.getValue();
        String busca = textoCodigoProduto.getText();
        String sql = "SELECT * FROM tb_produtos WHERE pro_codigo = " + busca + ";";
        try  (PreparedStatement ps = conexao.getConexao().prepareStatement(sql);
            ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    if(((rs.getInt("pro_quantidade") - quantidadeVenda) < 0)){
                        JOptionPane.showMessageDialog(this, "Quantidade indisponinel no estoque! Disponivel: " + rs.getInt("pro_quantidade"));
                        ps.close();
                        return;
                    }
                    Vector linha = new Vector();
                    linha.add(rs.getInt("pro_codigo"));
                    linha.add(rs.getString("pro_descricao"));
                    linha.add(quantidadeVenda);
                    linha.add(rs.getDouble("pro_valor"));
                    linha.add(rs.getDouble("pro_valor") * quantidadeVenda);
                    modelo.addRow(linha);
                }
                ps.close();
                if(modelo.getRowCount() == 0){
                    JOptionPane.showMessageDialog(this, "Produto com ID " + busca + " nao encontrado!");
                    return;
                }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        mostrarSubtotal.setText("R$ " + calcularSubtotal() + "0");
    }
    
    public double calcularSubtotal(){
        double subtotal = 0.00;
        for(int i = 0; i < modelo.getRowCount(); i++){
            subtotal = subtotal + (double)modelo.getValueAt(i, 4);
        }
        return subtotal;
    }
    
    public void realizarVenda(){
        double subtotal = calcularSubtotal();
        String sql = "";
        int cons_cod;
        String cons_desc;
        int cons_quantidade;
        String cpf = conexao.getCPF();
        for(int i = 0; i < modelo.getRowCount(); i++){
            cons_cod = (int)modelo.getValueAt(i, 0);
            cons_desc = (String)modelo.getValueAt(i, 1);
            cons_quantidade = (int)modelo.getValueAt(i, 2);
            sql = sql.concat("CALL vender_produto('" + cons_cod + "', '" + cons_desc + "', '" + cons_quantidade + "');");
        }
        sql = sql.concat("CALL registrar_venda('" + subtotal + "', '" + cpf + "');");
        try {
            PreparedStatement ps = conexao.getConexao().prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(this, "Venda realizada! Subtotal: R$ " + subtotal + "0");
            modelo.setRowCount(0);
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMostrarProdutosVendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textoCodigoProduto = new javax.swing.JTextField();
        seletorDeQuantidadeDeVenda = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        mostrarSubtotal = new javax.swing.JTextField();
        buttonConcluirVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelMensagemErroCodigo = new javax.swing.JLabel();
        jLabelMensagemErroQuantidade = new javax.swing.JLabel();
        jButtonAbrirHistorico = new javax.swing.JButton();
        jLabelMensagemErroTabelaVazia = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        tabelaMostrarProdutosVendas.setModel(modelo);
        tabelaMostrarProdutosVendas.setEnabled(false);
        jScrollPane1.setViewportView(tabelaMostrarProdutosVendas);
        if (tabelaMostrarProdutosVendas.getColumnModel().getColumnCount() > 0) {
            tabelaMostrarProdutosVendas.getColumnModel().getColumn(1).setResizable(false);
            tabelaMostrarProdutosVendas.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Produtos:");

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        jLabel3.setText("Código do Produto:");

        textoCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCodigoProdutoActionPerformed(evt);
            }
        });

        seletorDeQuantidadeDeVenda.setInheritsPopupMenu(true);
        seletorDeQuantidadeDeVenda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seletorDeQuantidadeDeVendaStateChanged(evt);
            }
        });

        jLabel4.setText("Subtotal");

        mostrarSubtotal.setEditable(false);
        mostrarSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        mostrarSubtotal.setText("R$ 0.00");
        mostrarSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSubtotalActionPerformed(evt);
            }
        });

        buttonConcluirVenda.setText("Concluir Venda");
        buttonConcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConcluirVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabelMensagemErroCodigo.setBackground(new java.awt.Color(214, 217, 223));
        jLabelMensagemErroCodigo.setForeground(new java.awt.Color(214, 217, 223));
        jLabelMensagemErroCodigo.setText("Insira o código!");

        jLabelMensagemErroQuantidade.setForeground(new java.awt.Color(214, 217, 223));
        jLabelMensagemErroQuantidade.setText("Insira uma quantidade!");

        jButtonAbrirHistorico.setText("Histórico");
        jButtonAbrirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirHistoricoActionPerformed(evt);
            }
        });

        jLabelMensagemErroTabelaVazia.setForeground(new java.awt.Color(214, 217, 223));
        jLabelMensagemErroTabelaVazia.setText("Adicione um produto!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabelMensagemErroCodigo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mostrarSubtotal)
                                .addComponent(buttonConcluirVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jButtonAbrirHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(textoCodigoProduto)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMensagemErroQuantidade)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonAdicionar)
                                            .addComponent(seletorDeQuantidadeDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelMensagemErroTabelaVazia)))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMensagemErroCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seletorDeQuantidadeDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdicionar)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelMensagemErroQuantidade)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonConcluirVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMensagemErroTabelaVazia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAbrirHistorico))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeOperadorActionPerformed

    private void menuArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArquivosActionPerformed

    private void menuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEstoqueActionPerformed

    private void mostrarSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarSubtotalActionPerformed

    private void seletorDeQuantidadeDeVendaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seletorDeQuantidadeDeVendaStateChanged
        if((int)seletorDeQuantidadeDeVenda.getValue() < 0){
            seletorDeQuantidadeDeVenda.setValue(0);
        }
    }//GEN-LAST:event_seletorDeQuantidadeDeVendaStateChanged

    private void textoCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCodigoProdutoActionPerformed
       // TODO: Implementar lógica para remover letras automaticamente
    }//GEN-LAST:event_textoCodigoProdutoActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        String codProduto = textoCodigoProduto.getText();
        
        if((int)seletorDeQuantidadeDeVenda.getValue() <= 0 ){
            jLabelMensagemErroQuantidade.setForeground(Color.red);
        } else{
            jLabelMensagemErroQuantidade.setForeground(new Color(214, 217, 223));
        }
        
        if(codProduto.isBlank()){
            jLabelMensagemErroCodigo.setForeground(Color.red);
        } else
        {
           jLabelMensagemErroCodigo.setForeground(new Color(214, 217, 223));
        }
        
        if(!((int)seletorDeQuantidadeDeVenda.getValue() <= 0 || codProduto.isBlank())){
            atualizarLista();
        }
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonConcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConcluirVendaActionPerformed
        if(modelo.getRowCount() == 0){
            jLabelMensagemErroTabelaVazia.setForeground(Color.red);
        } else{
            jLabelMensagemErroTabelaVazia.setForeground(new Color(214, 217, 223));
            realizarVenda();
        }
    }//GEN-LAST:event_buttonConcluirVendaActionPerformed

    private void jButtonAbrirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirHistoricoActionPerformed
        TelaHistoricoVenda telaHistoricoVenda = new TelaHistoricoVenda(conexao);
        telaHistoricoVenda.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirHistoricoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonConcluirVenda;
    private javax.swing.JButton jButtonAbrirHistorico;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMensagemErroCodigo;
    private javax.swing.JLabel jLabelMensagemErroQuantidade;
    private javax.swing.JLabel jLabelMensagemErroTabelaVazia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField mostrarSubtotal;
    private javax.swing.JSpinner seletorDeQuantidadeDeVenda;
    private javax.swing.JTable tabelaMostrarProdutosVendas;
    private javax.swing.JTextField textoCodigoProduto;
    // End of variables declaration//GEN-END:variables
}
