
package br.com.sistemas.userInterface;

import br.com.sistemas.model.database.ConexaoBDPostgres;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bastos
 */
public class TelaCadastroFornecedor extends javax.swing.JFrame {

    ConexaoBDPostgres conexao;
           
    public TelaCadastroFornecedor(ConexaoBDPostgres conexao) {

        this.conexao = conexao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk = new javax.swing.JButton();
        jLabelNomeFornecedor = new javax.swing.JLabel();
        jTextFieldDescricaoFornecedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelNomeFornecedor.setText("Nome Fornecedor:");

        jTextFieldDescricaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOk)
                    .addComponent(jTextFieldDescricaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescricaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoFornecedorActionPerformed
 
    }//GEN-LAST:event_jTextFieldDescricaoFornecedorActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        String fornecedor = jTextFieldDescricaoFornecedor.getText();
        try {
                    conexao.conectar();
                    PreparedStatement ps = null;
                    String sql = null; 
                    
                    // Cria o usuário e dá as permissões da funcao (role) pra ele.
                    // Prefixada e sufixada a letra u no nome do usuário pois o postgre não aceita usuários completamente numéricos
                    sql = "INSERT INTO tb_fornecedores(for_descricao) VALUES ('" + fornecedor + "');";        
                    ps = conexao.getConexao().prepareStatement(sql);
                    ps.executeUpdate();
                    
                    // Encerra a transação e mostra mensagam de sucesso
                    ps.close();
                    JOptionPane.showMessageDialog(null, "Registrado fornecedor " + fornecedor + " com sucesso!");
                    
                    //Desconecta e fecha
                    conexao.disconnect();
                    dispose(); // Auto-fecha janela de cadastro;
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }       
    }//GEN-LAST:event_jButtonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelNomeFornecedor;
    private javax.swing.JTextField jTextFieldDescricaoFornecedor;
    // End of variables declaration//GEN-END:variables
}
